[app]
name = "ayoles-portal"
version = "0.0.1"
host = "localhost"
port = 80
read_timeout = 5
write_timeout = 10
idle_timeout = 15

[server]
url = "https://warm-wave-76942.herokuapp.com/graphql"

[template]
path = "template/*.html"

[api]
credential = "credential/ayoles-19ba0cc86014.json"

[utils]
files = "files"
css = "files/css"
fonts = "files/fonts"
js = "files/js"